# Generated by Django 5.2 on 2025-04-29 16:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_attendance_status_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='performance',
            name='review_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='performance',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
